### ISSUE TITLE
screenname with the @ will always fail the "protected" test

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/distro#6]
This test (in helpers.py, pset 6):

    try:
        twitter = Twython(os.environ.get("API_KEY"), os.environ.get("API_SECRET"))
        user = twitter.lookup_user(screen_name=screen_name)
        if user[0]["protected"]:
            return None

appears to always fail if the screen_name passed to it contains the "@".

In application.py, we have provided code that strips that:

        screen_name = request.args.get("screen_name", "").lstrip("@")

such that `get_user_timeline` will work properly.

But we don't, as far as I can see, alert the students to the fact that the "@" must be stripped when they call `get_user_timeline` in their `tweets` program, which they are writing before they actually look at the `application.py` distro code.

Can we perhaps change that helpers.py code to say:

    user = twitter.lookup_user(screen_name=screen_name.lstrip("@"))

That seems to solve the problem.

**Comment by dmalan** [comment]
A good idea!

https://github.com/cs50/problems/blob/sentiments/helpers.py#L56
