### ISSUE TITLE
find's sorting algorithm

### ISSUE THREAD

**Issue by kzidane** [cs50/distro#7]
From time to time, some more-comfy student gets confused about the O of the sorting algorithm to be implemented. They're asked to implement an O(n) algorithm per the spec, but the comment in `helpers.c` says O(n^2).

```
// TODO: implement an O(n^2) sorting algorithm
```

https://github.com/cs50/problems/blob/222935ef5ca09a80d923be7e86bc49a237256e2f/helpers.c#L25

**Comment by dmalan** [comment]
https://github.com/cs50/problems/commit/3eea6d0aec86d598b6493db77037507e55195ed0!
